services:
  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
      POSTGRES_DB: order
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - data_local_postgres:/var/lib/postgresql/data
volumes:
  data_local_postgres:
  rabbitmq_data:
