// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID        int64
	OrderID   uuid.UUID
	Price     int32
	Status    string
	CreatedAt time.Time
	UpdatedAt *time.Time
}
