// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orders.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (order_id, price, status) VALUES ($1, $2, $3) RETURNING id, order_id, price, status, created_at, updated_at
`

type CreateOrderParams struct {
	OrderID uuid.UUID
	Price   int32
	Status  string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.OrderID, arg.Price, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
